package:
  name: pyflow
  version: 3.5.1
source:
  sha256: 4974afb7854cc326e57005fd14e115a41f4e01ff2abe88e52ad00204bc5ee583
  url: https://github.com/ecmwf/pyflow/archive/refs/tags/3.5.1.tar.gz
build:
  include_recipe: false
  number: 0
  script: $PYTHON -m pip install . --ignore-installed --no-cache-dir --no-deps -vvv
requirements:
  build:
    - pip
    - python
    - setuptools
  run:
    - ecflow
    - jinja2
    - requests
test:
  commands:
    - python -c "import pyflow"
about:
  license: APACHE
